ALTER TABLE `clients` ADD `cpf` VARCHAR(11) NOT NULL AFTER `name`, ADD `address` VARCHAR(1000) NULL AFTER `cpf`;

CREATE USER 'pobs'@'%' IDENTIFIED BY '***';GRANT USAGE ON *.* TO 'pobs'@'%' IDENTIFIED BY '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `pobs`.* TO 'pobs'@'%';